[package]
name = "midibox-sw"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["advanced", "canvas"] }
midir = "0.10.3"
num-traits = "0.2.19"
strum = { version = "0.27.2", features = ["derive"] }
